# Generated by Django 4.0.4 on 2023-12-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bn_name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('average_temperature', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.division')),
            ],
        ),
    ]
