# Generated by Django 4.0.4 on 2023-12-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='division_id',
            new_name='division',
        ),
    ]
